version: "3"

services:
  api:
    build: .
    command: "python api.py"
    ports:
      - 80:5000
    depends_on:
      - database
    environment:
      MYSQL_PASSWORD: secretPassword
      MYSQL_DATABASE: AOSW
    links:
      - database:database
  database:
    container_name: "database"
    build:
      dockerfile: Mysql
      context: ./mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretPassword
      MYSQL_DATABASE: AOSW
volumes:
  mysql_volume:
